######################################################################
# Automatically generated by qmake (2.01a) Mon Mar 26 18:48:05 2012
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .
LIBS += -lGLU
QT += opengl

# Input
HEADERS += ext_datatype.hh color.hh vector.hh qtglut.h scene.hh MainWindow.hh
FORMS += MainWindow.ui
SOURCES += ext_datatype.cc qtglut.cpp scene.cc MainWindow.cc main.cc
